### ISSUE TITLE
bug in heal-transparency, missing car

### ISSUE THREAD

**Issue by bootchk** [itr-tert/gimp-resynthesizer-scm-download#1]
There is a bug in heal-transparency scripts.

```
(set! org-selection (gimp-selection-save))   
should be  
(set! org-selection (car (gimp-selection-save)))
```
Also, thank you very much. 

I would like to correspond directly, please. But my email to what I think is your gmail account was not answered?

**Comment by itr-tert** [comment]
I will fix it.
thank you.

I checked my email address in the git log and it was valid (itr.tert+code@■■■.■■■).
I also checked my spam folder, but I couldn't find your email.
Please send the email again if you like.
